import { Footer } from '@/components/layout/footer/footer-main'
import { Header } from '@/components/layout/header/main-header'
import { ThemeProvider } from '@/components/layout/theme-provider'
import { Container } from '@/components/ui/container'
import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Container>
            <main className="px-2 md:px-6">{children}</main>
          </Container>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
